### PR TITLE
Re-export GlobalStrings and LocalizationStringsApi

### PR DESCRIPTION
**Pull request by cbrevik**
Make LocalizedStrings default export so we don't have to use `require`

### CODE REVIEW

**Comment by Fconstant** [comment]
There is a problem with this:
I've tried using `export default` before, but that won't work with `module.exports` exporting method. [Which is the case of this project](https://github.com/cbrevik/ReactNativeLocalization/blob/a1cd9dc8466d77a7facc3c00b5fa05872f1bcb8c/LocalizedStrings.js#L151).

Maybe adding a additional `exports.default = LocalizedStrings` to [this line](https://github.com/cbrevik/ReactNativeLocalization/blob/a1cd9dc8466d77a7facc3c00b5fa05872f1bcb8c/LocalizedStrings.js#L151) should work with TypeScript exporting method

**Comment by cbrevik** [comment]
Are you getting an error trying to do a `import LocalizedStrings from "react-native-localization"`?

This works fine in my React Native-projects with this module. Both for JavaScript and TypeScript. As far as I know, babel transpiles it to a `require` statement anyway. So I'm not sure why `import from` should fail?

Or am I misunderstanding something?

**Comment by Fconstant** [comment]
Could you please show me your `tsconfig.json` file?
I made a simple React-Native (0.48.0) project, and installed your branch `fix-typescript`.

This gave me this result:
RN Error

This is because TypeScript (using the default/common ts configuration) compiles this:
```typescript
import LocalizedStrings from "react-native-localization";
const strings = new LocalizedStrings({
    // ...
});
```
to this:
```javascript
var react_native_localization_1 = require("react-native-localization");
var strings = new react_native_localization_1.default({
    // ...
});
```
That's why I suggested the changes in my previous comment.

My `tsconfig.json`:
```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "lib": [ "es2015", "dom" ],
    "jsx": "react-native",
    "outDir": "lib",
    "rootDir": "src",
    "strict": true
  }
}
```

**Comment by cbrevik** [comment]
Aha, so that is why. My `tsconfig.json`:
```json
{
    "compilerOptions": {
        "target": "es2015",
        "module": "es2015",
        "jsx": "react-native",
        "moduleResolution": "node",
        "allowSyntheticDefaultImports": true,
        "allowJs": true,
        "noUnusedLocals": true,
        "experimentalDecorators": true
    }
}
```

It probably has to do with that you've set `"module": "commonjs"`. 

Also, do you build to a directory which you import in `index.android.js` & `index.ios.js` (`"outDir": "lib"`)? Doesn't that give you problems with hot reloading? I'd recommend trying to do it with a "transformer" along with the RN packager as I've outlined here; http://blog.novanet.no/easy-typescript-with-react-native/

Then you don't have to have a "dist" folder, and your compiled TS code is just automatically bundled with the rest of the app.

**Comment by Fconstant** [comment]
Oh, that worked very well. But I'm afraid not every people uses module resolution to `es2015`, and neither can we force them, how can we solve this?

I usually don't use the default React Packager, I like to use [Haul](https://github.com/callstack-io/haul), as it gives you full support for Webpack. And there I use a typescript loader, like `ts-loader` or `awesome-typescript-loader`. This change won't bother Haul users, will it? (I don't think so, as long as the `tsconfig.json` keeps the same module resolution)

**Comment by cbrevik** [comment]
Since this is React Native, isn't `es2015` modules, that is to say `import x from 'x'` the [recommended syntax anyway](https://stackoverflow.com/questions/37266515/does-react-native-use-require-or-import)? I'd think people should be using `es2015` and not `commonjs` for RN/TS-projects. 

I tried using Haul with TS, but to be completely honest I found it quite slow compared to the RN packager. I'd be interested in knowing what other benefits you found from using Haul/Webpack though. Are you using other loaders with Webpack as well?

As far as `allowSyntheticDefaultImports`, I haven't had any problems with it in any of my projects for dependencies.

**Comment by Fconstant** [comment]
> I tried using Haul with TS, but to be completely honest I found it quite slow compared to the RN packager. I'd be interested in knowing what other benefits you found from using Haul/Webpack though.

Funny thing, It's the opposite for me: Haul is a lot faster than RN Packager 😆  (At least at `react-native@^0.42`)

If this PR is merged, I think this TS requirements/changes should be pointed at the `README.md`

**Comment by cbrevik** [comment]
Aha, on packager startup you mean? The major speed difference I found were recompile of TypeScript on save/hot reload. Startup is a bit slow yeah. Cool that alternatives have popped up though!

Good idea, I can push an addition to the README in this PR as well 👍

**Comment by stefalda** [comment]
@cbrevik  could you please check if everything is ok after latest merge? because I don't use Typescript with RN and the declaration is changed again...

**Comment by cbrevik** [comment]
Oh, quite a bit has changed I see from the other PR. I'll review the changes :+1:

**Pull request merged**
