### PR TITLE
Added react-native 0.12.0-rc to peerDependencies

### PR DESCRIPTION
**Pull request by andreaskeller**
Hi Stefano,

Thanks for the module which we already used in two iOS apps. Now I am implementing the Android apps with react-native 0.12.0-rc. To be able to use the library with react-native 0.12.0-rc I had to extend the peerDependencies.

### CODE REVIEW

**Comment by stefalda** [comment]
I could merge the pull request but I'm not sure if it's correct, because then we should do the same for every next rc...

Opinions?

Thanks

**Comment by andreaskeller** [comment]
Yes that's true, but I don't think it's possible to specify a range which allows future rc-releases to be valid automatically, see http://semver.npmjs.com.

A possible alternative could be to remove the peerDependencies completely. What do you think?

There are react native packages without peerDependencies specified like [react-native-camera](https://github.com/lwansbrough/react-native-camera/blob/master/package.json), although until now I have added them for my components as well.

**Comment by stefalda** [comment]
Removing the  peerDependencies completely, that's what I was thinking too... I've heard in a podcast with npm creators that they should be used to request additional tools like gulp or grunt... so this could be the best solution...

Stefano

**Comment by andreaskeller** [comment]
I think that's the ideal solution. I changed my pull request to remove the peerDependencies.

**Pull request merged**
